# from galaxy
- src: geerlingguy.security
  version: 3.0.0

# TODO: replace with own role
# Source repository has been archived without explanation.
- src: jdauphant.nginx
  version: v2.21.2

- src: coopdevs.certbot_nginx
  version: v0.3.2

- src: oefenweb.swapfile
  version: v2.0.14

- src: geerlingguy.postgresql
  version: 3.5.2

- src: libre_ops.multi_redis
  version: 1.0.1

- src: arillso.logrotate
  version: 1.4.5
