---

domain: staging.openfoodnetwork.org.uk
host_id: uk-staging
rails_env: staging

admin_email: dev.ofnuk@gmail.com

users_sysadmin:
  - "{{ core_devs }}"
  - filipe
  - konrad
  - bethan

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_new_metabase }}"
  - "{{ custom_hba_new_metabase_IPv6 }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"

rack_timeout_term_on_timeout: 3

# VINE API settings
vine_api_url: "https://vine-staging.openfoodnetwork.org.au/api/v1"
