---

domain: openfood.hu
host_id: hu-prod # country initials (eg uk, es, de) and environment (default is prod)
rails_env: production

admin_email: pragai.robert@abasys.hu

# NOTE: custom pg_hba.conf and iptables are in use on the server, and the provision playbook will clobber them. 
# Please avoid  running the whole playbook if not necessary, and notify the above email if you do.
# See also thread: https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1722329658310779

mail_domain: pecsikosar.hu

# Optional list of subdomains to register in letsencrypt certificate
# Defaults to {{ domain }} if list is undefined
#
#certbot_domains:

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
#swapfile_size: 1G

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_new_metabase }}"
  - "{{ custom_hba_new_metabase_IPv6 }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"
#
#custom_env_vars: |
#  OFN_FEATURE_CONNECT_AND_LEARN="true"

# Overridable Image Settings
# attachment_url:
# attachment_path:

