---
domain: app.katuma.org
host_id: es-prod
rails_env: production

admin_email: info@katuma.org

mail_domain: katuma.org

certbot_domains:
  - app.katuma.org

certbot_cert_name: app.katuma.org

swapfile_size: 2G

enable_nginx_logging: true

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_metabase_IPv6 }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"
