---

domain: staging.coopcircuits.fr
host_id: fr-staging
rails_env: staging

admin_email: admin@coopcircuits.fr

mail_domain: coopcircuits.fr

users_sysadmin:
  - "{{ core_devs }}"
  - paco
  - filipe
  - konrad
  - mohamed

attachment_url: ccs-ofn-staging.s3.eu-west-3.amazonaws.com

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

# The default is `false`, not installing a swapfile.
swapfile_size: 1G

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_metabase_IPv6 }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"

# VINE API settings
vine_api_url: "https://vine-staging.openfoodnetwork.org.au/api/v1"
