---

# Make sure to insert secure passwords!!
db_password:
admin_password:

# Secret Token
# This is required to verify session. It must be at least 30 characters and
# random. This must be changed for a production server.
# Generate one with a bash command like: openssl rand -hex 128
secret_token: 'xxxxxx'

# Create a Google Maps API key and enable Javascript and Places libraries
google_maps_api_key:

# Mail settings
mail_host:
mail_port:
smtp_username:
smtp_password:

# Optional mail settings
## Connection type 'TLS' means STARTTLS usually on port 587
## Connection type 'SSL' means SSL/TLS usually on port 465
# mail_secure_connection: 'TLS'
# mails_from: from_address@example.com
# mail_bcc: bcc_me@example.com

# Set these if using Amazon S3 for images or backups
#s3_access_key:
#s3_secret:
# Set this if using Amazon S3 for images:
#s3_images_bucket:
# Set this if using Amazon S3 for backups:
#s3_backups_bucket:
# Optional settings for Amazon S3 for images:
#s3_headers:
#s3_protocol:
# Optional settings for Amazon S3 for backups:
#s3_backups_region:

# Stripe Connect API keys, set these if you are using Stripe
# Find these under 'API keys' and 'Connect' in your Stripe account dashboard -> Account Settings
# Under 'Connect', the Redirect URI should be set to https://YOUR_SERVER_URL/stripe/callbacks (e.g. https://openfoodnetwork.org.uk/stripe/callbacks)
# Under 'Webhooks', you should set up a Connect endpoint pointing to https://YOUR_SERVER_URL/stripe/webhooks e.g. (https://openfoodnetwork.org.uk/stripe/webhooks)
# Different keys can be made for testing or live environments
#stripe_client_id: # ca_xxxx
#stripe_instance_secret_key: # sk_xxxx
#stripe_instance_publishable_key: # pk_xxxx
#stripe_endpoint_secret: # whsec_xxxx

# Skylight's API key. This enables performance instrumentation through Skylight. See https://github.com/openfoodfoundation/openfoodnetwork/pull/2070 for details.
#skylight_authentication: ""

# Bugsnag collects all errors and notifies you.
# https://github.com/openfoodfoundation/ofn-install/wiki/Issue-reporting
#
#bugsnag_key: ''

# Example settings for integrations like Zapier.
# ----------------------------------------------
# Generate a strong password with this command: `openssl rand -hex 128`.
#
# You can add one or multiple entries using the lists (with dashes), then run
# the `db_integrations.yml` playbook on the target server.
#
# To disable an integration, change the `state` key from `present` to: `absent`,
# remove the custom_* entries, then run the db_integrations.yml playbook again.

#db_integrations:
#  - { user: zapier, state: present, password: incredibly_strong_password_goes_here }

# For using a geocoding service other than Google you will need:
#geocoder_api_key: pk.xxxx
#geocoder_service: mapbox
#geocoder_timeout: 7

## New Relic settings
#
# See: https://one.eu.newrelic.com/admin-portal/ > API keys
#
# Infrastructure agent:
#new_relic_api_key: "NRAK-XXXXXXXXXXXXXXXXXXXXXXXXXXX"
#new_relic_account_id: "0000000"
#new_relic_region: "EU"
#
# Rails APM:
#new_relic_agent_enabled: true
#new_relic_app_name: "Open Food Network"
#new_relic_license_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# database encryption configuration, required for vine connected app
# generate with bin/rails db:encryption:init
#active_record_encryption_primary_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#active_record_encryption_deterministic_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#active_record_encryption_key_derivation_salt: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
