---

domain: openfoodnetwork.ca
host_id: ca-prod
rails_env: production

admin_email: admin@openfoodnetwork.ca
mail_domain: openfoodnetwork.ca

puma_timeout: 120

certbot_domains:
  - openfoodnetwork.ca
  - www.openfoodnetwork.ca

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_new_n8n }}"
  - "{{ custom_hba_new_n8n_IPv6 }}"

enable_rails_apm: "false"
