---

domain: openfoodnetwork.org.uk
host_id: uk-prod
rails_env: production

puma_timeout: 120

certbot_domains:
  - openfoodnetwork.org.uk
  - www.openfoodnetwork.org.uk

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_new_n8n }}"
  - "{{ custom_hba_new_n8n_IPv6 }}"

attachment_url: ofn-uk-production.s3.us-east-1.amazonaws.com
