---

- name: Download installer
  ansible.builtin.get_url:
    url: "https://download.newrelic.com/install/newrelic-cli/scripts/install.sh"
    dest: "/tmp/new-relic-install.sh"
    mode: "777"

- name: Install New Relic command
  ansible.builtin.command: "/tmp/new-relic-install.sh"
  args:
    creates: /usr/local/bin/newrelic

- name: Install New Relic agent
  command: /usr/local/bin/newrelic install -y
  environment:
    NEW_RELIC_API_KEY: "{{ new_relic_api_key }}"
    NEW_RELIC_ACCOUNT_ID: "{{ new_relic_account_id }}"
    NEW_RELIC_REGION: "{{ new_relic_region }}"
  args:
    creates: /usr/bin/newrelic-infra

- name: Use our standard names in dashboard
  lineinfile:
    name: "/etc/newrelic-infra.yml"
    line: "display_name: {{ host_id }}"
    regex: "^display_name:"
    state: present
  notify: restart newrelic_infra

- name: Update new relic redis configuration # update redis port to monitor cache instance
  copy:
    content: |
      integrations:
        - name: nri-redis
          env:
            METRICS: true
            HOSTNAME: localhost
            PORT: 6379
            KEYS: 
            PASSWORD: ''
            CONFIG_INVENTORY: true
            KEYS_LIMIT: 30
            REMOTE_MONITORING: true
            USE_UNIX_SOCKET: false
          interval: 15s
          labels: 
            role: default 

        - name: nri-redis
          env:
            INVENTORY: true
            HOSTNAME: localhost
            PORT: 6379
            PASSWORD: ''
            REMOTE_MONITORING: true
            USE_UNIX_SOCKET: false
          inventory_source: config/redis
          interval: 60s
          labels: 
            role: default 

        - name: nri-redis
          env:
            METRICS: true
            HOSTNAME: localhost
            PORT: 6380
            KEYS: 
            PASSWORD: ''
            CONFIG_INVENTORY: true
            KEYS_LIMIT: 30
            REMOTE_MONITORING: true
            USE_UNIX_SOCKET: false
          interval: 15s
          labels: 
            role: cache 

        - name: nri-redis
          env:
            INVENTORY: true
            HOSTNAME: localhost
            PORT: 6380
            PASSWORD: ''
            REMOTE_MONITORING: true
            USE_UNIX_SOCKET: false
          inventory_source: config/redis
          interval: 60s
          labels: 
            role: cache 

        - name: nri-redis
          env:
            METRICS: true
            HOSTNAME: localhost
            PORT: 6381
            KEYS: 
            PASSWORD: ''
            CONFIG_INVENTORY: true
            KEYS_LIMIT: 30
            REMOTE_MONITORING: true
            USE_UNIX_SOCKET: false
          interval: 15s
          labels: 
            role: job 

        - name: nri-redis
          env:
            INVENTORY: true
            HOSTNAME: localhost
            PORT: 6381
            PASSWORD: ''
            REMOTE_MONITORING: true
            USE_UNIX_SOCKET: false
          inventory_source: config/redis
          interval: 60s
          labels: 
            role: job
    dest: /etc/newrelic-infra/integrations.d/redis-config.yml
    backup: true
  become: yes
  notify: restart newrelic_infra
