---

- name: Restore database from local machine
  hosts: ofn_servers
  remote_user: "{{ user }}"

  handlers:
    - import_tasks: ../roles/shared_handlers/handlers/main.yml

  roles:
    - role: db_restore
