---
- name: PostgreSQL production tuning
  hosts: ofn_servers
  remote_user: "{{ user }}"

  handlers:
    - import_tasks: ../roles/shared_handlers/handlers/main.yml

  roles:
    - role: postgres_tuning
      tags: postgres_tuning
