---
# Playbook for the initial setup of a new server before installing main packages.

# AWS ubuntu images generally have a default user (ubuntu) and wont let this be run as root.
# Use: `ansible-playbook playbooks/setup.yml -e "ansible_user=ubuntu" --limit <server_tag>` if
# provisioning an EC2 instance for the first time (this only needs to be run once).

# Add the default user and ssh keys as root
- name: set up default_user
  hosts: ofn_servers
  remote_user: root
  roles:
    - role: default_user
      become: yes
      tags: default_user

    - role: ssh_keys
      become: yes
      tags: ssh_keys

  tasks:
    - name: purge outdated nginx packages
      apt:
        name: nginx
        state: absent
        purge: yes
      become: yes
