---

domain: coopcircuits.fr
host_id: fr-prod
rails_env: production

admin_email: admin@coopcircuits.fr

mail_domain: coopcircuits.fr

puma_timeout: 120

certbot_domains:
  - coopcircuits.fr
  - www.coopcircuits.fr

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 1G

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_new_n8n }}"
  - "{{ custom_hba_new_n8n_IPv6 }}"

attachment_path: "home/openfoodnetwork/apps/openfoodnetwork/current/public/spree/products/:id/:style/:basename.:extension"
attachment_url: ofn-prod.s3.us-east-1.amazonaws.com
