---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: fi
currency: EUR
locale: fi                  # Default locale for OFN instance
available_locales: fi,en    # Available locales for OFN instance
language: fi_FI.UTF-8       # Default language for the server
language_packages:          # Language packages for the server
  - language-pack-en-base
l10n_repo: https://github.com/jarihu/l10n_fi.git
timezone: Helsinki


# Used for the LetsEncrypt email setting
developer_email: hello@openfoodnetwork.fi

# Users listed here will have their key from /files/keys added to the app_user
users_sysadmin:
  - jari-fi
